apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: link-shortener
    component: api
  annotations:
    repo: "https://github.com/truewebber/link-shortener"
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.api.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: link-shortener
    component: api
