apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: "link-shortener"
  annotations:
    repo: "https://github.com/truewebber/link-shortener"
    checksum/force-upgrade: {{ now | printf "%s" }}
spec:
  refreshInterval: "8760h" # 1 year, cause zero breaks force upgrade trigger
  secretStoreRef:
    kind: SecretStore
    name: gcp-secret-store
  target:
    name: "{{ .Release.Name }}-secret"
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app: "link-shortener"
        annotations:
          repo: "https://github.com/truewebber/link-shortener"
          checksum/external_secret: {{ now | printf "%s" }}
  data:
    - secretKey: postgres_connection_string
      remoteRef:
        key: link_shortener_postgres_connection_string
    # oauth_google
    - secretKey: oauth_google_client_id
      remoteRef:
        key: link_shortener_oauth_google_client_id
    - secretKey: oauth_google_client_secret
      remoteRef:
        key: link_shortener_oauth_google_client_secret
    # oauth_github
    - secretKey: oauth_github_client_id
      remoteRef:
        key: link_shortener_oauth_github_client_id
    - secretKey: oauth_github_client_secret
      remoteRef:
        key: link_shortener_oauth_github_client_secret
    # oauth_apple
    - secretKey: oauth_apple_client_id
      remoteRef:
        key: link_shortener_oauth_apple_client_id
    - secretKey: oauth_apple_private_key
      remoteRef:
        key: link_shortener_oauth_apple_private_key
    - secretKey: oauth_apple_key_id
      remoteRef:
        key: link_shortener_oauth_apple_key_id
    - secretKey: oauth_apple_team_id
      remoteRef:
        key: link_shortener_oauth_apple_team_id
