apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-frontend"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: link-shortener
    component: frontend
  annotations:
    repo: "https://github.com/truewebber/link-shortener"
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: link-shortener
      component: frontend
  template:
    metadata:
      labels:
        app: link-shortener
        component: frontend
      annotations:
        checksum/config: {{ .Values | toJson | sha256sum }}
    spec:
      imagePullSecrets:
        - name: dockerconfigjson-github-com
      containers:
        - name: frontend
          image: "ghcr.io/truewebber/link-shortener/frontend:{{ .Chart.AppVersion }}"
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - name: http
              containerPort: {{ .Values.frontend.port }}
              protocol: TCP
          env:
            - name: PORT
              value: "{{ .Values.frontend.port }}"
            - name: BACKEND_API_URL
              value: "{{ .Values.frontend.backendApiUrl }}"
            - name: ENVIRONMENT
              value: "{{ .Values.frontend.environment }}"
          livenessProbe:
            httpGet:
              port: {{ .Values.frontend.port }}
              path: /health
            initialDelaySeconds: 20
            timeoutSeconds: 15
          readinessProbe:
            httpGet:
              port: {{ .Values.frontend.port }}
              path: /health
            initialDelaySeconds: 15
            timeoutSeconds: 9
          resources:
            requests:
              memory: "20Mi"
              cpu: "20m"
            limits:
              memory: "40Mi"
              cpu: "40m"
