apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: "link-shortener"
  annotations:
    repo: "https://github.com/truewebber/link-shortener"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx-public
  tls:
    - hosts:
        - "{{ .Values.ingress.tls.host }}"
      secretName: "{{ .Values.ingress.tls.secretName }}"
  rules:
    - host: "{{ .Values.ingress.host }}"
      http:
        paths:
          # Frontend routes
          - path: /app
            pathType: Prefix
            backend:
              service:
                name: "{{ .Release.Name }}-frontend"
                port:
                  number: {{ .Values.frontend.port }}

          # API routes
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: "{{ .Release.Name }}-api"
                port:
                  number: {{ .Values.api.port }}

          # Root path for the frontend application
          - path: /
            pathType: Exact
            backend:
              service:
                name: "{{ .Release.Name }}-frontend"
                port:
                  number: {{ .Values.frontend.port }}

          # Static assets for the frontend
          - path: /assets
            pathType: Prefix
            backend:
              service:
                name: "{{ .Release.Name }}-frontend"
                port:
                  number: {{ .Values.frontend.port }}

          # URL redirection - this should be the last rule to catch all other paths
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Release.Name }}-api"
                port:
                  number: {{ .Values.api.port }}
