apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: link-shortener
    component: nginx
  annotations:
    repo: "https://github.com/truewebber/link-shortener"
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.nginx.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: link-shortener
    component: nginx
