apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: "link-shortener"
  annotations:
    repo: "https://github.com/truewebber/link-shortener"
stringData:
  postgres_connection_string: "{{ .Values.api.postgres_connection_string }}"
  oauth_google_client_id: "{{ .Values.api.oauth.google.client_id }}"
  oauth_google_client_secret: "{{ .Values.api.oauth.google.client_secret }}"
  oauth_github_client_id: "{{ .Values.api.oauth.github.client_id }}"
  oauth_github_client_secret: "{{ .Values.api.oauth.github.client_secret }}"
  oauth_apple_client_id: "{{ .Values.api.oauth.apple.client_id }}"
  oauth_apple_private_key: {{ .Values.api.oauth.apple.private_key | quote }}
  oauth_apple_key_id: "{{ .Values.api.oauth.apple.key_id }}"
  oauth_apple_team_id: "{{ .Values.api.oauth.apple.team_id }}"
  google_captcha_site_key: "{{ .Values.api.google_captcha_site_key }}"
  google_captcha_secret_key: "{{ .Values.api.google_captcha_secret_key }}"
