run:
  tests: true

output:
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  stylecheck:
    checks: ["all"]
  nolintlint:
    allow-unused: false
    require-explanation: true
    require-specific: true
  staticcheck:
    checks: ["all"]
  errcheck:
    check-type-assertions: true
    check-blank: true
  funlen:
    lines: 55
    statements: 30
  govet:
    enable-all: true
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/truewebber/link-shortener
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/truewebber/link-shortener)
      - blank
      - dot
    skip-generated: true
  gocyclo:
    min-complexity: 15
  gocognit:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 120
    tab-width: 1
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - whyNoLint
    settings:
      captLocal:
        paramsOnly: true
      rangeValCopy:
        sizeThreshold: 64

linters:
  enable-all: true
  disable:
    # deprecated
    - tenv
    # to consider in future
    - depguard
    # not helpful linters
    - varnamelen
    - exhaustruct
    - ireturn
    - tagliatelle

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        # Table tests are ok to have a lot of lines inside a function
        - funlen

        # Tests could have long lines due to provided test data
        - lll

        # Auto-generated tests may have cuddled assignments
        - wsl

        # Auto-generated tests may be using reflect.DeepEqual
        - govet

        # Tests may have small functions with defined errors instead of global vars
        - goerr113

        # Auto-generated table tests contain a context.Context field
        - containedctx

        # Test might to be bulky
        - maintidx

        # Tests or cases could be similar
        - dupl

    # For white-box testing
    - path: _internal_test\.go
      linters:
        - testpackage

    # Generate lines may be long
    - linters:
        - lll
      source: "^//go:generate "