services:
  postgres:
    image: postgres:16-alpine
    container_name: link-shortener-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: link_shortener
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    container_name: link-shortener-migrate
    volumes:
      - ./sql:/migrations
    command: ["-path", "/migrations", "-database", "postgres://postgres:postgres@postgres:5432/link_shortener?sslmode=disable", "up"]
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: 