ingress:
  tls:
    host: "short.twb.one"
    secretName: "short-twb-one-tls"
  host: "short.twb.one"

api:
  replicaCount: 1
  port: 9999
  metricsPort: 9998

frontend:
  replicaCount: 1
  port: 3000
  environment: "production"
  backendApiUrl: "/"
