INSERT INTO users (provider_type,
                   provider_user_id,
                   provider_user_email,
                   provider_user_name,
                   provider_avatar_url,
                   created_at,
                   updated_at,
                   deleted)
VALUES ('anonymous',
        '-1',
        '',
        'default',
        '',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP,
        FALSE);
