name: Frontend CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  lint:
    name: Flutter Lint
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x.x'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: |
          cd web
          flutter pub get

      - name: Analyze code
        run: |
          cd web
          flutter analyze --no-fatal-infos

  test:
    name: Flutter Test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x.x'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: |
          cd web
          flutter pub get

      - name: Run tests
        run: |
          cd web
          flutter test

  build:
    name: Build and Push Docker Images
    runs-on: self-hosted
    needs: [ test, lint ]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master' && success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/frontend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
