name: link_shortener
description: A modern URL shortening service with enhanced features for registered users.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.3.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.14
  flutter_svg: ^2.0.7
  intl: ^0.20.2
  clipboard: ^0.1.3
  google_fonts: ^6.2.1
  universal_html: ^2.2.4
  localstorage: ^4.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.5
  build_runner: ^2.4.15
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
